// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('main', []);
x$.controller('section', ['$scope', '$element', 'skolto'].concat(function($scope, $element, skolto){
  var id;
  $scope.q2Age = [1, 2, 4, 8, 16, 32, 48, 56, 49, 47, 31, 15, 7, 3];
  $scope.q3Count = [11432, 3501, 583, 5, 1];
  $scope.q4Count = [23, 55, 5, 10];
  $scope.q5Count = [23, 55, 5, 10];
  $scope.q6Count = [25175, 45000, 45965, 55000, 62475];
  $scope.finalCount = [1, 3, 45, 120, 99, 65, 23, 4];
  $scope.cid = id = $element.attr('id');
  $scope.chosen = 0;
  $scope.$watch('$parent.ans', function(){
    if (!isNaN($scope.$parent.ans[id])) {
      $element.addClass('finish');
    }
    if ($scope.$parent.ans[id]) {
      return $element.addClass('active');
    }
  }, true);
  return $scope.choice = function(value, nid, ans){
    var name;
    $scope.chosen = value;
    $scope.$parent.ans[id] = value;
    $scope.$parent.ans[nid] = {};
    skolto(nid);
    name = ans ? 'right' : 'wrong';
    console.log($scope.$parent.sound[name].play);
    return setTimeout(function(){
      var x$;
      x$ = $scope.$parent.sound[name];
      x$.load();
      x$.play();
      return x$;
    }, 100);
  };
}));
x$.controller('main', ['$scope', 'randomFact', 'skolto'].concat(function($scope, randomFact, skolto){
  var addsound, i$, i, img, lresult$, j$, j, results$ = [];
  setTimeout(function(){
    return $('#footer').sticky({
      topSpacing: 0
    });
  }, 0);
  $scope.randomFact = randomFact();
  $scope.ans = {
    Q1: {}
  };
  $scope.ans = {
    Q1: {},
    Q2: {},
    Q3: {},
    Q4: {},
    Q5: {},
    Q6: {},
    Q7: {},
    Q8: {}
  };
  $scope.skolto = function(nid){
    return skolto(nid, 0);
  };
  addsound = function(name){
    var node, ref$;
    node = document.createElement('audio');
    node.appendChild((ref$ = document.createElement('source'), ref$.src = "sound/" + name + ".ogg", ref$.type = "audio/ogg", ref$));
    node.appendChild((ref$ = document.createElement('source'), ref$.src = "sound/" + name + ".mp3", ref$.type = "audio/mpeg", ref$));
    return node;
  };
  $scope.sound = {
    wrong: addsound('wrong'),
    right: addsound('right')
  };
  for (i$ = 1; i$ <= 8; ++i$) {
    i = i$;
    img = new Image();
    img.src = "img/chief/Q" + i + ".png";
  }
  for (i$ = 1; i$ <= 5; ++i$) {
    i = i$;
    lresult$ = [];
    for (j$ = 1; j$ <= 4; ++j$) {
      j = j$;
      img = new Image();
      lresult$.push(img.src = "img/choice/" + i + j + ".png");
    }
    results$.push(lresult$);
  }
  return results$;
}));