// Generated by LiveScript 1.2.0
var x$;
x$ = angular.module('main');
x$.factory('skolto', function(){
  return function(des, delay){
    delay == null && (delay = 500);
    return setTimeout(function(){
      var target;
      target = $("#" + des);
      return $("html,body").animate({
        scrollTop: target.offset().top
      }, 500);
    }, delay);
  };
});
x$.factory('randomFact', function($http){
  return function(){
    var ret, i;
    ret = (function(){
      var i$, to$, results$ = [];
      for (i$ = 0, to$ = parseInt(Math.random() * 10) + 5; i$ <= to$; ++i$) {
        i = i$;
        results$.push(parseInt(Math.random() * 100));
      }
      return results$;
    }()).map(function(it){
      var s;
      s = sentence[it];
      return s[parseInt(Math.random() * s.length)];
    });
    return ret.join("，") + "。";
  };
});
x$.directive('delayBk', function(){
  return {
    restrict: 'A',
    link: function(scope, e, attrs, ctrl){
      var url;
      url = attrs["delayBk"];
      return $('<img/>').attr('src', url).load(function(){
        $(this).remove();
        e.css({
          "background-image": "url(" + url + ")"
        });
        return setTimeout(function(){
          return e.toggleClass('visible');
        }, 100);
      });
    }
  };
});